### ISSUE TITLE
Any plans on releasing code?

### ISSUE THREAD

**Issue by pieris98** [pvnieo/NCP#1]
Dear Souhaib,
Are there any plans to release (at least part of the network) code of NCP?
Thanks in advance and thank you for your contributions to the field!

**Comment by hiyyg** [comment]
`coming soon` means `> 2 years`

**Comment by pvnieo** [comment]
Dear @pieris98 

Thanks for waiting!
I'll put a notebook illustrating the effect by the end of next week!

In the meantime, do you have a specific thing you need about this code?

**Comment by pvnieo** [comment]
Dear @pieris98 

I updated the repo, please let me know if you have any questions!
